package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// JobsInterface is interface for /jobs root endpoint
type JobsInterface interface { // Post is the handler for POST /jobs
	// Create a job
	Post(http.ResponseWriter, *http.Request)
}

// JobsInterfaceRoutes is routing for /jobs root endpoint
func JobsInterfaceRoutes(r *mux.Router, i JobsInterface) {
	r.HandleFunc("/jobs", i.Post).Methods("POST")
}
