package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// ResourcesInterface is interface for /resources root endpoint
type ResourcesInterface interface { // Get is the handler for GET /resources
	// Get a resource
	Get(http.ResponseWriter, *http.Request)
	// Post is the handler for POST /resources
	// Post a resource
	Post(http.ResponseWriter, *http.Request)
	// resourceIdGet is the handler for GET /resources/{resourceId}
	// Get a resource ID
	resourceIdGet(http.ResponseWriter, *http.Request)
	// resourceIdPut is the handler for PUT /resources/{resourceId}
	// Put resource ID
	resourceIdPut(http.ResponseWriter, *http.Request)
	// resourceIdDelete is the handler for DELETE /resources/{resourceId}
	// Delete a resource ID
	resourceIdDelete(http.ResponseWriter, *http.Request)
	// resourceIdyet_anotherGet is the handler for GET /resources/{resourceId}/yet_another
	// Yet another
	resourceIdyet_anotherGet(http.ResponseWriter, *http.Request)
}

// ResourcesInterfaceRoutes is routing for /resources root endpoint
func ResourcesInterfaceRoutes(r *mux.Router, i ResourcesInterface) {
	r.HandleFunc("/resources", i.Get).Methods("GET")
	r.HandleFunc("/resources", i.Post).Methods("POST")
	r.HandleFunc("/resources/{resourceId}", i.resourceIdGet).Methods("GET")
	r.HandleFunc("/resources/{resourceId}", i.resourceIdPut).Methods("PUT")
	r.HandleFunc("/resources/{resourceId}", i.resourceIdDelete).Methods("DELETE")
	r.HandleFunc("/resources/{resourceId}/yet_another", i.resourceIdyet_anotherGet).Methods("GET")
}
