package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"github.com/justinas/alice"
	"net/http"
)

// UsersInterface is interface for /users root endpoint
type UsersInterface interface { // Get is the handler for GET /users
	// Get list of all developers
	Get(http.ResponseWriter, *http.Request)
	// Post is the handler for POST /users
	// Add user
	Post(http.ResponseWriter, *http.Request)
	// usernameGet is the handler for GET /users/{username}
	// Get information on a specific user
	usernameGet(http.ResponseWriter, *http.Request)
}

// UsersInterfaceRoutes is routing for /users root endpoint
func UsersInterfaceRoutes(r *mux.Router, i UsersInterface) {
	r.Handle("/users", alice.New(NewOauth2itsyouonlineMiddleware([]string{}).Handler).Then(http.HandlerFunc(i.Get))).Methods("GET")
	r.HandleFunc("/users", i.Post).Methods("POST")
	r.Handle("/users/{username}", alice.New(NewOauth2itsyouonlineMiddleware([]string{}).Handler).Then(http.HandlerFunc(i.usernameGet))).Methods("GET")
}
